### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by josh-degraw** [josh-degraw/gleam#1]
# Features

## MVP
- [ ] #3
- [x] Write code in a Gleam project, and build a .NET DLL
- [ ] Write code in a Gleam project, and build an executable file via AOT
- [ ] #2
  - [ ] Ensure any referenced project uses the sdtlib fork instead of the original

## Nice to have
- [ ] Custom MsBuild targets to directly reference a compiled Gleam project from a .NET project
- [ ] Codegen for importing .NET code into a Gleam project to limit the amount of necessary `@external` functions
